### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by bharati-21** [euhidaman/zomato-clone#3]
Hey @euhidaman,
I have noticed that this application is not responsive in screen below 1000px or so. I would like to work on this! 

Thanks.

**Comment by euhidaman** [comment]
Sure!!

You can go ahead and create a pull request with all the changes that you want to make.

**Comment by bharati-21** [comment]
> Sure!!
> 
> You can go ahead and create a pull request with all the changes that you want to make.

Hi @euhidaman , I needed a little help with the responsive design of "FoodOptions" section. So I thought that as the screen size reduced, the colored line could be added for the current selection as a border.


This is the original (in proper desktop size) 
![image](https://user-images.githubusercontent.com/51514137/136755186-abdbee9b-8d93-47f6-93f3-3a77e4633f23.png)


And this is the original (when screen size is lowered)
![image](https://user-images.githubusercontent.com/51514137/136755366-bb6932ba-29a0-4e23-9b4e-aab533fc29a3.png)


And this is the changes I made (to make the food options container as a grid, when screen size becomes slower)
![image](https://user-images.githubusercontent.com/51514137/136755524-338e6aab-60bd-4d46-a95f-25af44ea5a18.png)




- When screen size is lowered, and the "Food options" component gets squished, I turned the container into a grid, as well as ensured that the <ColoredLine> component was made to width and height of 0. Is this fine, or do you have another way to do this in mind?

**Comment by euhidaman** [comment]
**Wow, this looks really good !!☺**

But @bharati-21 , do make sure to do **fetch upstream to remove any merge conflicts**, as many changes has been done to this project, in the past few days.

Also, it would be really good, if the **original(in proper desktop size) header** could stay the same like this -->
![Screenshot_3](https://user-images.githubusercontent.com/65843257/136757368-dda74f12-fcdf-45b7-b332-f47e1db5e6c5.jpg)
i.e, the words and symbols in the FilterButtons.js component, remain in the same line(as shown in above pic).


Looking forward to your contribution !!

**Comment by bharati-21** [comment]
> **Wow, this looks really good !!☺**
> 
> But @bharati-21 , do make sure to do **fetch upstream to remove any merge conflicts**, as many changes has been done to this project, in the past few days.
> 
> Also, it would be really good, if the **original(in proper desktop size) header** could stay the same like this --> ![Screenshot_3](https://user-images.githubusercontent.com/65843257/136757368-dda74f12-fcdf-45b7-b332-f47e1db5e6c5.jpg) i.e, the words and symbols in the FilterButtons.js component, remain in the same line(as shown in above pic).
> 
> Looking forward to your contribution !!

Thank you 👍🏽 
Okay, thanks for informing about the new changes. I'll fetch right away to avoid conflicts.

Yes, I'll work on the FilterButtons like you suggested to ensure text and symbols are in the same line. Haven't begun that yet. I'm going component by component from top to bottom 👍🏽 .

**Comment by bharati-21** [comment]
Another question I have in mind is, are you planning to extend this project into a fully fledged working application (i.e. with frontend to let users interact and back end)?

**Comment by euhidaman** [comment]
> Another question I have in mind is, are you planning to extend this project into a fully fledged working application (i.e. with frontend to let users interact and back end)?

Yes, I am planning to set up a basic backend, in the later stages of this project.
Either with **Firebase**, or **Django**.

**Comment by bharati-21** [comment]
> > Another question I have in mind is, are you planning to extend this project into a fully fledged working application (i.e. with frontend to let users interact and back end)?
> 
> Yes, I am planning to set up a basic backend, in the later stages of this project. Either with **Firebase**, or **Django**.

Hi @euhidaman,
Thank you!
So I'm done with the responsive style, but unfortunately there are merge conflicts. Once resolved, I shall make a PR.

Thanks!

**Comment by euhidaman** [comment]
Sure, take your time !!
In the meantime, I'll put the `hacktoberfest-accepted` label on your pull request, because I know you are doing a meaningful contribution !!

**Comment by bharati-21** [comment]
> Sure, take your time !! In the meantime, I'll put the `hacktoberfest-accepted` label on your pull request, because I know you are doing a meaningful contribution !!

Hi @euhidaman,
Thank you! I really appreciate it.

I also noticed that somebody has already worked on the responsiveness of a few components.
I wanted to know if I need to retain those changes, or is it fine if I override my changes for responsive design.

Thanks!

**Comment by euhidaman** [comment]
Well, a few other people have worked on the responsiveness of the body of the website.
And, it would be good, if the functionality of their work stays.
That is, it doesn't matter what changes you make to the code, but the overall responsiveness of the website must stay.

Also, the new features of the website, must not be destroyed or removed in any way, such as the `search` feature.

**Comment by bharati-21** [comment]
> Well, a few other people have worked on the responsiveness of the body of the website. And, it would be good, if the functionality of their work stays. That is, it doesn't matter what changes you make to the code, but the overall responsiveness of the website must stay.
> 
> Also, the new features of the website, must not be destroyed or removed in any way, such as the `search` feature.

Okay so actually right now, the filter options, and food option have a scroll bar if they overflow. But I have worked on them to wrap into the next line as the screen size reduces. If you choose one of the two I shall make changes accordingly. 

Another thing is the header. In my responsive change drops, there's a drop down menu for sign up and login, but in the one merged into the repo (main), there's no dropdown, just the buttons. 

This is the current design:
![image](https://user-images.githubusercontent.com/51514137/138678887-2abc6a01-6ba9-4bd7-b802-110a5d8866aa.png)

This is the design changes that I made:
![image](https://user-images.githubusercontent.com/51514137/138679045-9d9ab953-6462-4b81-851b-9b1e0cc04b07.png)

Which ever you want me to add as the final change, I shall add that.


As for the search functionality, I do not seem to see any suggestions:
![image](https://user-images.githubusercontent.com/51514137/138679237-04317be0-9b26-414a-b520-ab6d80221418.png)

**Comment by euhidaman** [comment]
Your responsive design of the Header, looks better. You can add that.

And, as for the search function, this is how it will look -->
![Screenshot_3](https://user-images.githubusercontent.com/65843257/138680439-2685c7c5-8f51-4481-8011-1bb91071e10a.jpg)
You must type everything in lowercase for the functionality to work.

Also, currently the food images are not being shown, because I have used the Unsplash API, and maintenance is going on the Unsplash website currently.

**Comment by bharati-21** [comment]
> Your responsive design of the Header, looks better. You can add that.
> 
> And, as for the search function, this is how it will look --> ![Screenshot_3](https://user-images.githubusercontent.com/65843257/138680439-2685c7c5-8f51-4481-8011-1bb91071e10a.jpg) You must type everything in lowercase for the functionality to work.
> 
> Also, currently the food images are not being shown, because I have used the Unsplash API, and maintenance is going on the Unsplash website currently.

Okay, thank you!
What of filter buttons and the food options?

**Comment by euhidaman** [comment]
You can add your design. The one where, they all go down each other, under a specific screen resolution.
This one : 
![image](https://user-images.githubusercontent.com/51514137/138679045-9d9ab953-6462-4b81-851b-9b1e0cc04b07.png)

**Comment by euhidaman** [comment]
@bharati-21 I would like to tell you that, a new feature has been added to the website again, to sort the restaurant details based on their `Ratings`. (Check out this pull request, for more details #11 )
So, when doing the necessary changes to the codebase, make sure to incorporate the new features too.

**Comment by bharati-21** [comment]
> @bharati-21 I would like to tell you that, a new feature has been added to the website again, to sort the restaurant details based on their `Ratings`. (Check out this pull request, for more details #11 ) So, when doing the necessary changes to the codebase, make sure to incorporate the new features too.

Yes, thank you!
I also request you to give me a few hours, and kindly not merge any other PR for the time being! I shall make a PR soon, because this was the 2nd time I had to resolve merge conflicts. 😅

**Comment by bharati-21** [comment]
Hey @euhidaman,
I have created a PR. Kindly review. 👍🏽

**Comment by euhidaman** [comment]
I have merged your pull request !!
Thank you for working so hard on this project, and making it responsive !! 😄

I am closing this issue now !

**Comment by bharati-21** [comment]
> I have merged your pull request !! Thank you for working so hard on this project, and making it responsive !! 😄
> 
> I am closing this issue now !

Hey @euhidaman,
Thank you for giving me the opportunity to work on this project! 😄
